#include "planstrssxfem.h"
#include "engngm.h"

Interface *
PlaneStress2dXfem :: giveInterface(InterfaceType interface) {
    if ( interface == XfemElementInterfaceType ) {
        return ( XfemElementInterface * ) this;
    }

    return NULL;
}

void PlaneStress2dXfem :: XfemElementInterface_createEnrBmatrixAt(GaussPoint *gp, FloatMatrix &answer) {
    // transformation of gauss point into global coordinates
    FloatArray gpGlob;
    interpolation.local2global(gpGlob, this->giveDomain(), dofManArray, * gp->giveCoordinates(), 0.0);
    // evaluation of N,dNdx
    FloatMatrix dNdx;
    interpolation.evaldNdx(dNdx, domain, dofManArray, * gp->giveCoordinates(), 0.0);
    FloatArray N;
    interpolation.evalN(N, * gp->giveCoordinates(), 0.0);
    XfemManager *xf = this->giveDomain()->giveEngngModel()->giveXfemManager(1);
    IntArray interactedEI;
    xf->getInteractedEI(interactedEI, this);
    for ( int i = 1; i <= interactedEI.giveSize(); i++ ) {
        EnrichmentItem *er = xf->giveEnrichmentItem( interactedEI.at(i) );
        int erndofs = er->giveNumberOfDofs();
        // enrichment function at the global gauss point
        FloatArray efgp;
        er->giveEnrichmentFunction()->evaluateFunctionAt(efgp, & gpGlob);
        // derivative of enrichment function at the global gauss point
        FloatMatrix efgpD;
        er->giveEnrichmentFunction()->evaluateDerivativeAt(efgpD, & gpGlob);
        // adds up the number of the dofs from an enrichment item
        int enrCount = 0;
        // for each node
        for ( int j = 1; j <= this->giveNumberOfDofManagers(); j++ ) {
            if ( er->isDofManEnriched( this->giveDofManagerNumber(j) ) ) {
                enrCount += erndofs;
                FloatArray *nodecoords = domain->giveDofManager( dofManArray.at(j) )->giveCoordinates();
                // ef is a FloatArray containing the value of EnrichmentFunction in a specific for all enriched dofs
                FloatArray efnode;
                er->giveEnrichmentFunction()->evaluateFunctionAt(efnode, nodecoords);
                // matrix to be added anytime a node is enriched
                FloatMatrix toAdd(3, erndofs);
                toAdd.zero();
                FloatArray help;
                help.resize(2);
                for ( int p = 1; p <= 2; p++ ) {
                    help.at(p) = dNdx.at(j, p) * ( efgp.at(1) - efnode.at(1) ) + N.at(j) * efgpD.at(p, p);
                }

                for ( int k = 1; k <= erndofs; k++ ) {
                    toAdd.at(k, k) = help.at(k);
                    if ( k == 1 ) {
                        toAdd.at(3, k) = help.at(2);
                    }

                    if ( k == 2 ) {
                        toAdd.at(3, k) = help.at(1);
                    }
                }

                // there is some problem here with resizeWithData
                answer.resizeWithData(3, enrCount);
                answer.addSubMatrix(toAdd, 1, enrCount);
            }
        }
    }
}

void PlaneStress2dXfem :: giveLocationArray(IntArray &locationArray, EquationID) {
    IntArray interactedEI;
    XfemManager *xf = this->giveDomain()->giveEngngModel()->giveXfemManager(1);
    xf->getInteractedEI(interactedEI, this);
    // for all enrichment items which element interacts
    for ( int i = 1; i <= interactedEI.giveSize(); i++ ) {
        EnrichmentItem *er = xf->giveEnrichmentItem( interactedEI.at(i) );
        IntArray *dofIdAr = er->getDofIdArray();
        // for all of the element nodes
        for ( int j = 1; j <= this->giveNumberOfDofManagers(); j++ ) {
            int erndofs = er->giveNumberOfDofs();
            // for all the enrichment number dofs
            for ( int k = 1; k <= erndofs; k++ ) {
                // giveEquationNumber needs to be generated by computeFictPosition at XfemManager
                /*
                 *               int eqN = this->giveDofManager(j)->giveDofWithID(dofIdAr->at(i))->giveEquationNumber();
                 *               locationArray.followedBy(eqN);
                 */
            }
        }
    }
}
