/*
 *
 *                 #####    #####   ######  ######  ###   ###
 *               ##   ##  ##   ##  ##      ##      ## ### ##
 *              ##   ##  ##   ##  ####    ####    ##  #  ##
 *             ##   ##  ##   ##  ##      ##      ##     ##
 *            ##   ##  ##   ##  ##      ##      ##     ##
 *            #####    #####   ##      ######  ##     ##
 *
 *
 *             OOFEM : Object Oriented Finite Element Code
 *
 *               Copyright (C) 1993 - 2025   Borek Patzak
 *
 *
 *
 *       Czech Technical University, Faculty of Civil Engineering,
 *   Department of Structural Mechanics, 166 29 Prague, Czech Republic
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
#ifndef mpmevaluator_h
#define mpmevaluator_h

#include <iostream>
#include <vector>
#include <string>
#include <variant>
#include <map>
#include <functional>
#include <stack>
#include <regex>
#include <sstream>
#include <cmath> 
#include <stdexcept>
#include "floatmatrix.h"

using namespace std;

namespace oofem {
    /**
 * @file mpmevaluator2.h
 * @brief A high-performance, lightweight scripting Virtual Machine (VM) designed specifically 
 * for Finite Element Analysis (FEA) and matrix mathematics.
 *
 * =================================================================================================
 * ARCHITECTURAL OVERVIEW
 * =================================================================================================
 * The solution implements a two-stage pipeline: Compilation and Execution. This design separates
 * the costly parsing logic from the performance-critical mathematical evaluation, making it ideal
 * for FEA loops where the same formula is evaluated millions of times with different data.
 *
 * 

[Image of compiler-vm architecture diagram]

 *
 * 1. COMPILER (FEAScriptCompiler)
 * - Parses string scripts containing mathematical expressions, assignments, and logic.
 * - Uses a custom Tokenizer (Regex-based) and the Shunting-Yard algorithm to handle operator precedence.
 * - Generates a linear "Bytecode" (std::vector<Instruction>).
 * - Implements "Copy Elision": Intermediate results are written directly to their final 
 * destination in the memory pool, avoiding unnecessary temporary copies.
 * - Detects and handles Matrix Literals (e.g., [[1,0],[0,1]]), Slicing (e.g., A[0,1]), 
 * and Control Flow (e.g., if(cond, true, false)).
 *
 * 2. EVALUATOR (FEAScriptEvaluator)
 * - A stack-less, register-based VM that executes the generated bytecode.
 * - Uses a pre-allocated "Memory Pool" (std::vector<VarSlot>) to store all constants, 
 * variables, and temporary results. This ensures zero heap allocations during runtime execution.
 * - Supports "Functors": External C++ functions (e.g., constitutive material laws) can be 
 * registered and called directly from the script.
 *
 * =================================================================================================
 * KEY FEATURES & CAPABILITIES
 * =================================================================================================
 * - Type System: Dynamic typing using std::variant<double, Eigen::MatrixXd>. 
 * Automatically promotes/demotes types (e.g., 1x1 Matrix -> Scalar).
 * - Matrix Math: Multiplication (*), Addition (+), Subtraction (-), Transpose (.T), Unary Minus (-).
 * - Broadcasting: Supports operations between Scalars and Matrices (e.g., Matrix - 1.0).
 * - Slicing: Robust Python-like slicing for elements (A[i,j]), rows (A[i,:]), and columns (A[:,j]).
 * - Logic & Control: Full support for boolean operators (&&, ||), comparisons (>, <, ==, !=), 
 * and ternary logic (if-else).
 * - Safety: Runtime tracking of uninitialized variables via an 'is_set' bitmask to prevent 
 * undefined behavior.
 *
 * =================================================================================================
 * USAGE PATTERN
 * =================================================================================================
 * 1. Compile: 
 * MPMCompiler compiler;
 * compiler.compile_script("R = K * u", program, symbols, ...);
 * 2. Setup VM: 
 * MPMEvaluator vm(pool_size, symbols);
 * 3. Bind Data: 
 * vm.set_variable("K", stiffness_matrix);
 * vm.set_variable("u", displacement_vector);
 * 4. Execute: 
 * vm.execute(program);
 * 5. Retrieve: 
 * auto result = vm.get_result();
 */




/** 
 * --- FEA VM CORE TYPES ---
 * Dynamic typing allows matrices to change shape during runtime, 
 * which is essential for element-specific calculations.
 */

/**
 * @enum VarType
 * @brief Supported data types within the VM pool.
 */
using VarData = std::variant<double, FloatMatrix, void*>;

/**
 * @struct VarSlot
 * @brief Atomic memory unit in the VM's pre-allocated pool.
 */
struct VarSlot {
    enum class Type { SCALAR, MATRIX, USER_PTR } type = Type::SCALAR;
    VarData value = 0.0;
};

using Functor = std::function<void(const std::vector<const VarSlot*>&, VarSlot&)>;

/**
 * @brief OpCode
 * The instruction set for our virtual machine.
 * MAT_SLICE: Extracts rows, columns, or elements.
 * COPY: Efficient assignment.
 * LOGIC_OP: Comparisons for future conditional logic.
 */
enum class OpCode { 
    CALL_FUNC,    // Invoke external C++ Functor
    MAT_SLICE,    // Slice Matrix: A[0,1] or A[:,0]
    MAT_ADD,      // Matrix+Matrix or Scalar+Scalar
    MAT_SUB,      // Subtraction (supports broadcasting)
    MAT_MUL,      // Multiplication (Dot product or Scalar scale)
    MAT_NEG,      // Unary Minus
    MAT_TRANS,    // Transpose (.T)
    COPY,         // Variable Assignment
    CMP_EQ, CMP_GT, CMP_LT, // Comparisons (==, >, <)
    LOGIC_AND, LOGIC_OR,    // Boolean Logic (&&, ||)
    OP_IF         // Ternary Condition: if(cond, true, false)
};
/**
 * @brief Instruction
 * A flat bytecode instruction.
 * @param func_name Used for Functor lookup (CALL_FUNC) or Debugging.
 * @param inputs    Indices of arguments in the pool (for functions/if).
 * @param lhs_idx   Optimized index for Binary LHS.
 * @param rhs_idx   Optimized index for Binary RHS.
 * @param output_idx Destination slot index.
 */
struct Instruction {
    OpCode op;
    std::string func_name; 
    std::vector<int> inputs;    // Indices of input arguments in the memory pool
    int lhs_idx = -1;           // Left-hand side operand index
    int rhs_idx = -1;           // Right-hand side operand index
    int output_idx = -1;            // Output operand index
};

/**
 * @class MPMCompiler
 * @brief Parses infix strings and emits optimized Bytecode.
 * * The compiler utilizes a Shunting-Yard algorithm to resolve operator precedence.
 * It maps variables and constants to fixed memory slots to eliminate runtime 
 * allocations during the execution phase.
 * * 
 */
class MPMCompiler {
    // Operator Precedence (Higher = Tighter binding)
    std::map<std::string, int> precedence = {
        {".T", 10}, {"unary-", 9}, 
        {"*", 8}, {"+", 7}, {"-", 7},
        {"==", 6}, {"!=", 6}, {">", 6}, {"<", 6}, {">=", 6}, {"<=", 6},
        {"&&", 5}, {"||", 4}           
    };
    std::map<std::string, bool> func_registry;

    // Helper: Is the previous token an operand? (Used to distinguish Slices vs Literals)
    bool is_operand(const std::string& t) {
        if (t.empty()) return false;        
        // ADDED: t[0] == '[' 
        // This allows the parser to see [[1,2]] as data that can be sliced immediately.
        return (t == ")" || t == ".T" || t[0] == ']' || t[0] == '[' || isalnum(t[0]));
    }

    public:
    /**
     * @brief Registers a function name for the parser to recognize.
     * @param name The string name of the function (e.g., "K", "if", "sin").
     */
    void register_function(std::string name) { func_registry[name] = true; }
    /**
     * @brief Compiles an infix math expression into VM instructions.
     * * @param script The mathematical string (e.g., "u.T * K * u").
     * @param program [out] Vector to be filled with generated instructions.
     * @param symbols [in/out] Mapping of variable names to pool indices.
     * @param constants [out] Mapping of pool indices to literal values found in string.
     * @param pool_ptr [in/out] Current tail of the memory pool.
     */
    void compile_script(std::string script, std::vector<Instruction>& program, 
                       std::map<std::string, int>& symbols, std::map<int, VarData>& constants, int& pool_ptr) {
        std::stringstream ss(script);
        std::string segment;
        
        while (std::getline(ss, segment, ';')) {
            if (segment.find_first_not_of(" \t\n\r") == std::string::npos) continue;

            // --- ROBUST ASSIGNMENT SCANNER ---
            size_t eq_pos = std::string::npos;
            for (size_t i = 0; i < segment.size(); ++i) {
                if (segment[i] == '=') {
                    // Ignore '=='
                    if (i + 1 < segment.size() && segment[i+1] == '=') { i++; continue; }
                    // Ignore '>=', '<=', '!='
                    if (i > 0 && (segment[i-1] == '>' || segment[i-1] == '<' || segment[i-1] == '!')) { continue; }
                    
                    eq_pos = i; // Found true assignment
                    break;
                }
            }

            if (eq_pos != std::string::npos) {
                // ASSIGNMENT: var = expr
                std::string var_name = segment.substr(0, eq_pos);
                std::string expr = segment.substr(eq_pos + 1);
                
                var_name.erase(0, var_name.find_first_not_of(" "));
                var_name.erase(var_name.find_last_not_of(" ") + 1);
                
                if (symbols.find(var_name) == symbols.end()) symbols[var_name] = pool_ptr++;
                compile_expression(expr, program, symbols, constants, pool_ptr, symbols[var_name]);
            } else {
                // NAKED EXPRESSION: expr
                compile_expression(segment, program, symbols, constants, pool_ptr, pool_ptr++);
            }
        }
    }

private:
    void compile_expression(std::string expr, std::vector<Instruction>& program, 
                          std::map<std::string, int>& symbols, std::map<int, VarData>& constants, int& pool_ptr, int target_slot) {
        
        // Regex: Matches Matrices [[..]], Slices [..], Logic (&&, ||), Comparisons (>=, ==), Math, Parens
        //std::regex re(R"(\[\[.*?\]\]|\[.*?\]|[a-zA-Z_]\w*|\d*\.?\d+|&&|\|\||==|!=|>=|<=|>|<|\.T|\+|\-|\*|\(|\)|,)");
        // Added (?:[eE][+-]?\d+)? to the number matching block
        // std::regex re(R"(\[\[.*?\]\]|\[.*?\]|[a-zA-Z_]\w*|\d*\.?\d+(?:[eE][+-]?\d+)?|&&|\|\||==|!=|>=|<=|>|<|\.T|\+|\-|\*|\(|\)|,)");
        // Added support for enum literals (e.g., MatResponseMode::Stress)
        std::regex re(R"(\[\[.*?\]\]|\[.*?\]|[a-zA-Z_]\w*(?:::\w+)*|\d*\.?\d+(?:[eE][+-]?\d+)?|&&|\|\||==|!=|>=|<=|>|<|\.T|\+|\-|\*|\(|\)|,)");
        auto it = std::sregex_token_iterator(expr.begin(), expr.end(), re);
        std::vector<std::string> tokens(it, std::sregex_token_iterator());

        std::vector<std::string> rpn;
        std::stack<std::string> ops;
        std::stack<int> arg_count_stack; 
        std::string last = "(";

        for (const std::string& t : tokens) {
            // 1. Matrix Literal or Slice
            if (t[0] == '[') {
                if (is_operand(last)) parse_slice(t, rpn, constants, pool_ptr);
                else parse_literal(t, rpn, constants, pool_ptr);
            } 
            // 2. Functions & 'if'
            else if (func_registry.count(t) || t == "if") {
                ops.push(t); arg_count_stack.push(0);
            } 
            // 3. Parentheses
            else if (t == "(") { 
                // --- NEW: Detect if the user is trying to call an undeclared function ---
                if (std::isalpha(last[0]) && last != "if" && !func_registry.count(last)) {
                    throw std::runtime_error("Compiler Error: Unregistered function '" + last + "()'");
                }
                ops.push(t); }
            else if (t == ")") {
                while (!ops.empty() && ops.top() != "(") { rpn.push_back(ops.top()); ops.pop(); }
                if (!ops.empty()) ops.pop(); 
                
                // Function Argument Count Handling
                if (!ops.empty() && (func_registry.count(ops.top()) || ops.top() == "if")) {
                    int ac = 0;
                    if(!arg_count_stack.empty()) { ac = arg_count_stack.top(); arg_count_stack.pop(); }
                    rpn.push_back(ops.top() + "#" + std::to_string(ac));
                    ops.pop();
                }
            } 
            // 4. Argument Separator
            else if (t == ",") {
                while (!ops.empty() && ops.top() != "(") { rpn.push_back(ops.top()); ops.pop(); }
                if (!arg_count_stack.empty()) arg_count_stack.top()++;
            } 
            // 5. Operators
            else if (precedence.count(t)) {
                std::string op = t;
                if (t == "-" && (last == "(" || last == ",")) op = "unary-";
                while (!ops.empty() && ops.top() != "(" && precedence.count(ops.top()) && precedence[ops.top()] >= precedence[op]) {
                    rpn.push_back(ops.top()); ops.pop();
                }
                ops.push(op);
            } 
            // 6. Operands
            else { 
                rpn.push_back(t); 
                if (!arg_count_stack.empty() && arg_count_stack.top() == 0) arg_count_stack.top() = 1;
            }
            last = t;
        }
        while (!ops.empty()) { rpn.push_back(ops.top()); ops.pop(); }
        
        emit_bytecode(rpn, program, symbols, constants, pool_ptr, target_slot);
    }

    void parse_literal(std::string t, std::vector<std::string>& rpn, std::map<int, VarData>& constants, int& pool_ptr) {
        std::string content = t.substr(1, t.size() - 2); 
        std::vector<std::vector<double>> rows;
        std::regex row_re(R"(\[(.*?)\])");
        auto row_it = std::sregex_iterator(content.begin(), content.end(), row_re);       
        for (std::sregex_iterator i = row_it; i != std::sregex_iterator(); ++i) {
            std::stringstream ss((*i)[1].str());
            std::string val; std::vector<double> r_vals;
            while (std::getline(ss, val, ',')) r_vals.push_back(std::stod(val));
            rows.push_back(r_vals);
        }

        FloatMatrix m(rows.size(), rows[0].size());
        for(std::size_t i=0; i<rows.size(); ++i)
            for(std::size_t j=0; j<rows[0].size(); ++j) m(i,j) = rows[i][j];

        int slot = pool_ptr++; constants[slot] = m;
        rpn.push_back("__CONST_MAT__" + std::to_string(slot));
    }

    void parse_slice(std::string t, std::vector<std::string>& rpn, std::map<int, VarData>& constants, int& pool_ptr) {
        std::string content = t.substr(1, t.size() - 2);
        std::stringstream ss(content);
        std::string seg; int count = 0;
        while (std::getline(ss, seg, ',')) {
            seg.erase(0, seg.find_first_not_of(" "));
            if (seg == ":") {
                int slot = pool_ptr++; constants[slot] = -1.0;
                rpn.push_back("__CONST__" + std::to_string(slot));
            } else { rpn.push_back(seg); }
            count++;
        }
        rpn.push_back("SLICE#" + std::to_string(count));
    }

    void emit_bytecode(std::vector<std::string>& rpn, std::vector<Instruction>& program, 
                       std::map<std::string, int>& symbols, std::map<int, VarData>& constants, int& pool_ptr, int final_target) {
        std::stack<int> eval_stack;
        for (size_t i = 0; i < rpn.size(); ++i) {
            std::string t = rpn[i];
            bool is_last = (i == rpn.size() - 1);    
            size_t h_pos = t.find('#');
            if (h_pos != std::string::npos) {
                std::string name = t.substr(0, h_pos);
                int n = std::stoi(t.substr(h_pos + 1));
                std::vector<int> args(n);
                for (int j = n - 1; j >= 0; --j) { args[j] = eval_stack.top(); eval_stack.pop(); }            
                int out = is_last ? final_target : pool_ptr++;

                if (name == "SLICE") {
                    int target = eval_stack.top(); eval_stack.pop();
                    std::vector<int> in = {target}; in.insert(in.end(), args.begin(), args.end());
                    program.push_back({OpCode::MAT_SLICE, "SLICE", in, -1, -1, out});
                } else if (name == "if") {
                    program.push_back({OpCode::OP_IF, "IF", args, -1, -1, out});
                } else {
                    program.push_back({OpCode::CALL_FUNC, name, args, -1, -1, out});
                }
                eval_stack.push(out);
            } else if (precedence.count(t)) {
                int r = eval_stack.top(); eval_stack.pop();
                int out = is_last ? final_target : pool_ptr++;
                
                if (t == ".T") {
                    program.push_back({OpCode::MAT_TRANS, ".T", {}, -1, r, out});
                } else if (t == "unary-") {
                    program.push_back({OpCode::MAT_NEG, "NEG", {}, -1, r, out});
                } else {
                    int l = eval_stack.top(); eval_stack.pop();
                    OpCode op;
                    if (t == "&&") op = OpCode::LOGIC_AND;
                    else if (t == "||") op = OpCode::LOGIC_OR;
                    else if (t == "==") op = OpCode::CMP_EQ;
                    else if (t == ">") op = OpCode::CMP_GT;
                    else if (t == "<") op = OpCode::CMP_LT;
                    else if (t == "*") op = OpCode::MAT_MUL;
                    else if (t == "+") op = OpCode::MAT_ADD;
                    else op = OpCode::MAT_SUB;        
                    program.push_back({op, t, {}, l, r, out});
                }
                eval_stack.push(out);
            } else {
                int slot;
                if (t.find("__CONST_MAT__") == 0) slot = std::stoi(t.substr(13));
                else if (t.find("__CONST__") == 0) slot = std::stoi(t.substr(9));
                else if (isdigit(t[0]) || (t.size() > 1 && t[0] == '.')) {
                     slot = pool_ptr++; constants[slot] = std::stod(t); 
                } else {
                    if (symbols.find(t) == symbols.end()) symbols[t] = pool_ptr++;
                    slot = symbols[t];
                }
                eval_stack.push(slot);
                if (is_last) program.push_back({OpCode::COPY, "COPY", {}, -1, slot, final_target});
            }
        }
        // --- NEW: Validate the final Abstract Syntax Tree ---
        if (eval_stack.size() != 1) {
            throw std::runtime_error("Compiler Error: Invalid expression syntax. Missing operator between variables?");
        }
    }
};


/**
 * @class MPMEvaluator
 * @brief The execution engine that processes Bytecode instructions.
 * *The Evaluator maintains the VarSlot pool and handles the mathematical kernels 
 * via OOFEM routines. It supports "broadcasting," where a scalar can be added/subtracted 
 * from a matrix element-wise automatically.
 * *
 */
class MPMEvaluator {
    std::vector<VarSlot> pool;
    // PARALLEL ARRAY FOR TRACKING INITIALIZATION STATUS
    std::vector<bool> is_set; 

    std::map<std::string, int> symbol_table;
    std::map<std::string, Functor> functors;
        int last_output_idx = 0; 

    bool to_bool(const VarSlot& s) {
        //if (s.type == VarSlot::Type::MATRIX) return false; 
        if (s.type == VarSlot::Type::MATRIX || s.type == VarSlot::Type::USER_PTR) return false;
        return std::abs(std::get<double>(s.value)) > 1e-12;
    }

    // --- SAFETY CHECK HELPER ---
    void check_init(int idx) const {
        if (idx < 0 || idx >= (int)is_set.size()) throw std::runtime_error("VM Error: Index out of bounds");
        if (!is_set[idx]) throw std::runtime_error("Runtime Error: Use of uninitialized variable at index " + std::to_string(idx));
    }

    // ADDED: Prevents accidental math on raw pointers (e.g., ptr + 5)
    void check_math_type(const VarSlot& s) const {
        if (s.type == VarSlot::Type::USER_PTR) {
            throw std::runtime_error("Runtime Error: Cannot perform arithmetic on generic void* pointer.");
        }
    }

public:
    /**
     * @brief Constructs an evaluator with a fixed memory footprint.
     * @param sz Total number of slots required for variables, constants, and intermediates.
     * @param syms The symbol table generated during compilation.
     */
    MPMEvaluator(int sz, std::map<std::string, int> syms) : pool(sz), is_set(sz, false), symbol_table(syms) {}
    /**
     * @brief Injects a C++ function into the VM environment.
     * @param name Name of the function as it appears in the expression string.
     * @param f Lambda or function pointer following the Functor signature.
     */
    void register_functor(std::string name, Functor f) { functors[name] = f; }

    // Internal Initialization (Sets flag to true)
    void init_slot(int idx, VarData val) {
        pool[idx].value = val;
        //pool[idx].type = std::holds_alternative<double>(val) ? VarSlot::Type::SCALAR : VarSlot::Type::MATRIX;
        if (std::holds_alternative<double>(val)) pool[idx].type = VarSlot::Type::SCALAR;
        else if (std::holds_alternative<FloatMatrix>(val)) pool[idx].type = VarSlot::Type::MATRIX;
        else pool[idx].type = VarSlot::Type::USER_PTR; // Handle void*
        is_set[idx] = true;
    }

    // Public API
    /*
    void set_variable(std::string name, VarData val) {
        if (symbol_table.count(name)) init_slot(symbol_table.at(name), val);
        else throw std::runtime_error("Variable '" + name + "' not found in script symbols.");
    }
    */
    /**
     * @brief Safely attempts to bind a variable to the memory pool.
     * @param name The string identifier of the variable.
     * @param val The data to inject (double, MatrixXd, or void*).
     * @return true if the script uses this variable and it was bound, false if ignored.
     */
    bool set_variable(const std::string& name, VarData val) {
        auto it = symbol_table.find(name);
        if (it != symbol_table.end()) {
            init_slot(it->second, val);
            return true;
        }
        // Silently ignore variables that the script doesn't care about
        return false; 
    }
    
    VarSlot get_result() { 
        check_init(last_output_idx);
        return pool[last_output_idx]; 
    }



    /**
     * @brief Runs the compiled instruction set.
     * @param program Vector of instructions to execute.
     * @throw std::runtime_error if dimension mismatches occur during matrix ops.
     */
    void execute(const std::vector<Instruction>& program) {
        if (program.empty()) return;
        last_output_idx = program.back().output_idx; 

        for (const auto& instr : program) {
            VarSlot& O = pool[instr.output_idx];
            
            // Mark output as initialized AFTER successful execution logic
            // Note: We perform check_init on inputs inside the switch

            switch (instr.op) {
                case OpCode::COPY: 
                    check_init(instr.rhs_idx); 
                    O = pool[instr.rhs_idx]; 
                    break;
                
                case OpCode::MAT_NEG: {
                    check_init(instr.rhs_idx);
                    const auto& src = pool[instr.rhs_idx];
                    check_math_type(src); // Safety check
                    if (src.type == VarSlot::Type::MATRIX) { O.value = FloatMatrix(std::get<FloatMatrix>(src.value)); std::get<FloatMatrix>(O.value).negated();O.type = VarSlot::Type::MATRIX; } 
                    else { O.value = -std::get<double>(src.value); O.type = VarSlot::Type::SCALAR; }
                    break;
                }
                case OpCode::MAT_TRANS: { 
                    check_init(instr.rhs_idx);
                    const auto& src = pool[instr.rhs_idx];
                    check_math_type(src); // Safety check
                    if (src.type == VarSlot::Type::MATRIX) { O.value=FloatMatrix::fromMatrix(std::get<FloatMatrix>(src.value), true); O.type = VarSlot::Type::MATRIX; }
                    else O = src;
                    break; 
                }
                case OpCode::MAT_MUL: {
                    check_init(instr.lhs_idx); check_init(instr.rhs_idx);
                    const VarSlot &L = pool[instr.lhs_idx], &R = pool[instr.rhs_idx];
                    check_math_type(L); // Safety check
                    check_math_type(R); // Safety check
                    if (L.type == VarSlot::Type::SCALAR && R.type == VarSlot::Type::MATRIX) {
                        O.value = FloatMatrix(std::get<double>(L.value) * std::get<FloatMatrix>(R.value)); O.type = VarSlot::Type::MATRIX;
                    } else if (L.type == VarSlot::Type::MATRIX && R.type == VarSlot::Type::MATRIX) {
                        const auto &m1 = std::get<FloatMatrix>(L.value), &m2 = std::get<FloatMatrix>(R.value);
                        if (m1.cols() != m2.rows()) {
                            throw std::runtime_error("Matrix Multiplication size mismatch");
                        }
                        auto res = m1 * m2;
                        //if (res.rows() == 1 && res.cols() == 1) { O.value = res(0,0); O.type = VarSlot::Type::SCALAR; }
                        //else { O.value = res; O.type = VarSlot::Type::MATRIX; }
                        O.value = res; O.type = VarSlot::Type::MATRIX;
                    } else if (L.type == VarSlot::Type::MATRIX && R.type == VarSlot::Type::SCALAR) {
                        O.value =  FloatMatrix(std::get<double>(R.value) * std::get<FloatMatrix>(L.value));; O.type = VarSlot::Type::MATRIX;
                    } else { O.value = std::get<double>(L.value) * std::get<double>(R.value); O.type = VarSlot::Type::SCALAR; }
                    break;
                }
                case OpCode::MAT_ADD: 
                case OpCode::MAT_SUB: {
                    check_init(instr.lhs_idx); check_init(instr.rhs_idx);
                    const VarSlot &L = pool[instr.lhs_idx], &R = pool[instr.rhs_idx];
                    check_math_type(L); // Safety check
                    check_math_type(R); // Safety check
                    bool is_add = (instr.op == OpCode::MAT_ADD);
                    if (L.type == VarSlot::Type::MATRIX && R.type == VarSlot::Type::MATRIX) {
                        const auto &m1 = std::get<FloatMatrix>(L.value), &m2 = std::get<FloatMatrix>(R.value);
                        if (m1.rows() != m2.rows() || m1.cols() != m2.cols()) throw std::runtime_error("Addition Dimension Mismatch");
                        O.value = is_add ? FloatMatrix(m1 + m2) : FloatMatrix(m1 - m2);
                        O.type = VarSlot::Type::MATRIX;
                    } else if (L.type == VarSlot::Type::SCALAR && R.type == VarSlot::Type::SCALAR) {
                        O.value = is_add ? std::get<double>(L.value) + std::get<double>(R.value)
                                         : std::get<double>(L.value) - std::get<double>(R.value);
                        O.type = VarSlot::Type::SCALAR;
                    } else { // Broadcasting
                        throw std::runtime_error("Matrix scalar addition/substraction not supported");
                        /*
                        double s = (L.type == VarSlot::Type::SCALAR) ? std::get<double>(L.value) : std::get<double>(R.value);
                        const auto& m = (L.type == VarSlot::Type::MATRIX) ? std::get<FloatMatrix>(L.value) : std::get<FloatMatrix>(R.value);
                        if (is_add) O.value = FloatMatrix(m.array() + s);
                        else O.value = (L.type == VarSlot::Type::SCALAR) ? FloatMatrix(s - m.array()) : FloatMatrix(m.array() - s);
                        O.type = VarSlot::Type::MATRIX;
                        */
                    }
                    break; 
                }
                case OpCode::MAT_SLICE: {
                    check_init(instr.inputs[0]); check_init(instr.inputs[1]); check_init(instr.inputs[2]);
                    check_math_type(pool[instr.inputs[0]]); // Safety check
                    const auto& m = std::get<FloatMatrix>(pool[instr.inputs[0]].value);
                    int r = (int)std::get<double>(pool[instr.inputs[1]].value);
                    int c = (int)std::get<double>(pool[instr.inputs[2]].value);
                    if (r == -1) { O.value = FloatMatrix(m.col(c)); O.type = VarSlot::Type::MATRIX; }
                    else if (c == -1) { O.value = FloatMatrix(m.row(r)); O.type = VarSlot::Type::MATRIX; }
                    else { O.value = m(r, c); O.type = VarSlot::Type::SCALAR; }
                    break;
                }
                case OpCode::CALL_FUNC: {
                    std::vector<const VarSlot*> args; 
                    for (int idx : instr.inputs) { check_init(idx); args.push_back(&pool[idx]); }
                    functors.at(instr.func_name)(args, O); 
                    break;
                }
                case OpCode::CMP_GT: 
                case OpCode::CMP_LT:
                case OpCode::CMP_EQ: {
                    check_init(instr.lhs_idx); check_init(instr.rhs_idx);
                    double l = std::get<double>(pool[instr.lhs_idx].value);
                    double r = std::get<double>(pool[instr.rhs_idx].value);
                    bool res = (instr.op == OpCode::CMP_GT) ? l > r : (instr.op == OpCode::CMP_LT) ? l < r : std::abs(l-r) < 1e-9;
                    O.value = res ? 1.0 : 0.0; O.type = VarSlot::Type::SCALAR;
                    break;
                }
                case OpCode::LOGIC_AND: 
                case OpCode::LOGIC_OR: {
                    check_init(instr.lhs_idx); check_init(instr.rhs_idx);
                    bool l = to_bool(pool[instr.lhs_idx]), r = to_bool(pool[instr.rhs_idx]);
                    O.value = (instr.op == OpCode::LOGIC_AND) ? (l && r ? 1.0 : 0.0) : (l || r ? 1.0 : 0.0);
                    O.type = VarSlot::Type::SCALAR;
                    break;
                }
                case OpCode::OP_IF: {
                    check_init(instr.inputs[0]); 
                    // Note: Eager evaluation in current instruction set means inputs 1 and 2 are usually already initialized if calculated.
                    // But if they are raw variables, we must check.
                    check_init(instr.inputs[1]); check_init(instr.inputs[2]);
                    O = to_bool(pool[instr.inputs[0]]) ? pool[instr.inputs[1]] : pool[instr.inputs[2]];
                    break;
                }
            }
            // Mark destination as set
            is_set[instr.output_idx] = true;
        }
    }
};



} // namespace oofem
#endif // mpmevaluator_h