#ifndef PRESCRIBEDGRADIENTWEAKQUADTETNODALFORCE_H
#define PRESCRIBEDGRADIENTWEAKQUADTETNODALFORCE_H

class PrescribedGradientWeakQuadTetNodalForce
{
public:
    PrescribedGradientWeakQuadTetNodalForce();
};

#endif // PRESCRIBEDGRADIENTWEAKQUADTETNODALFORCE_H
